const mockInterviewData = [
  {
    companyName: "Nomura",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Tell me about your family background",
          "Where are you currently residing?",
          "What are your hobbies?",
          "Who inspires you?",
          "Why do you want to work at Nomura?",
          "What are your strengths and weaknesses?",
          "What is your biggest achievement?",
          "Have you faced any failure? How did you handle it?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain your project in detail",
          "Explain the architecture and workflow of your project",
          "Why did you choose this project?",
          "What technologies did you use and why?",
          "How does the frontend communicate with the backend?",
          "Explain REST APIs",
          "Explain OOP concepts",
          "Explain SQL concepts like WHERE clause and joins",
          "Difference between SQL and NoSQL databases",
          "Explain SDLC and Agile methodology",
          "How did you handle challenges in your project?",
          "How would you improve or scale your project in the future?",
        ],
      },
    ],
  },
  {
    companyName: "RippleHire",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Why do you want to work at RippleHire?",
          "What do you know about RippleHire and what we do?",
          "Tell me about a challenge you faced",
          "How do you handle pressure?",
          "What are your hobbies?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain OOP concepts",
          "Difference between JDK, JRE, and JVM",
          "Difference between Stack memory and Heap memory",
          "What is unit testing?",
          "What is regression testing?",
          "Explain SQL joins",
          "What are SQL constraints?",
          "Explain your project",
          "What challenges did you face in your project?",
        ],
      },
    ],
  },
  {
    companyName: "Accenture",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Why do you want to work at Accenture?",
          "Tell me about your internships",
          "Tell me about your family background",
          "What kind of position would you like in Accenture?",
          "What if you don’t get your preferred role?",
          "How did you handle any difficulty in your internship or academic life?",
          "Have you ever faced failure? How did you deal with it?",
          "What are your hobbies?",
          "Any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain OOP concepts",
          "What is unit testing?",
          "What is regression testing?",
          "Explain SQL joins",
          "What is DBMS?",
          "Explain normalization",
          "What is pseudocode?",
          "Explain basics of MS Office tools like Excel or Word",
          "Explain your project in detail",
          "What challenges did you face in your project?",
          "How would you improve your project?",
          "How would you use technology or data science to solve real-world problems?",
        ],
      },
    ],
  },
  {
    companyName: "Alpha Alternatives",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Introduce yourself",
          "Tell me about your family background",
          "Where are you currently staying?",
          "Reflect on how you found the interview process",
          "What technologies would you like to work with?",
          "Do you know the tech stack the company works with?",
          "Are you open to learning new technologies?",
          "What motivates you to join Alpha Alternatives?",
          "What are your long-term career goals?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain your project in detail",
          "Explain the data flow of your project",
          "How did you implement authentication in your project?",
          "Why did you choose this tech stack?",
          "Explain OOP concepts with real-world examples",
          "Explain SQL clauses like WHERE and HAVING",
          "What are aggregate functions in SQL?",
          "Difference between WHERE and HAVING clause",
          "Explain system design basics",
          "Design a web application like an investment tracking or banking system",
          "Explain functional and non-functional requirements",
          "How would you handle authentication in a large-scale system?",
          "How would you design the database for such a system?",
          "How would you approach scalability and performance?",
        ],
      },
    ],
  },
  {
    companyName: "CleverTap",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Where do you currently stay?",
          "Why do you want to join CleverTap?",
          "What do you know about CleverTap as a company?",
          "What are your strengths and weaknesses?",
          "What are your long-term career goals?",
          "Are you comfortable with relocation or shift timings?",
          "Why should we hire you?",
          "How do you handle new or unfamiliar situations?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain your projects in detail",
          "Walk me through the data flow of your project",
          "What technologies did you use and why?",
          "Explain OOP concepts",
          "Explain error and exception handling",
          "Explain SQL basics",
          "Explain REST APIs and their use",
          "Explain Android basics conceptually",
          "Explain the Android activity lifecycle",
          "What is a Toast in Android?",
          "How do you approach scenario-based problems?",
          "How do you communicate technical solutions to non-technical stakeholders?",
          "Why did you choose this role over a pure development role?",
        ],
      },
    ],
  },
  {
    companyName: "Clariant",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Where are you from?",
          "What are your strengths and weaknesses?",
          "Where have you applied your strengths in real life or work?",
          "How do you handle work under tight deadlines?",
          "Tell us about your previous experience or internship",
          "Why are you interested in Clariant?",
          "Are you comfortable working in roles related to SAP or supply chain?",
          "Where do you see yourself in 5 years?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "What programming languages are you familiar with?",
          "Explain your projects mentioned in the resume",
          "Explain SQL concepts like normalization",
          "How would you rate yourself in SQL or Python?",
          "Have you used Git or GitHub in your projects?",
          "Explain how you debug issues in your projects",
          "Are you familiar with SAP-related technologies?",
          "What cloud technologies are you aware of?",
          "How frequently do you use tools like ChatGPT in your work?",
          "Are you okay if you don’t get a pure coding role initially?",
        ],
      },
    ],
  },
  {
    companyName: "Saint Gobain",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "What are your interests and hobbies?",
          "Which was the last web series or match you watched?",
          "Why do you want to join Saint Gobain?",
          "What do you know about the company?",
          "What are your strengths and weaknesses?",
          "Name three qualities of a leader and a manager",
          "Difference between a leader and a manager",
          "Would you be a better leader or manager? Why?",
          "What is the biggest achievement of your life?",
          "What is the biggest regret of your life?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain your project in detail",
          "Which architecture did you use in your project?",
          "Why did you choose Spring Boot over Spring?",
          "Explain DispatcherServlet",
          "Explain the Spring Boot annotations used in your project",
          "Where did you define the business logic?",
          "What is JPA?",
          "Why did you use Hibernate as an ORM?",
          "Do you know any other ORM frameworks?",
          "How did you connect frontend with the database?",
          "How did you configure your project?",
          "Explain SQL concepts like primary key and normalization",
          "Explain how well you understand your project APIs and database schema",
        ],
      },
    ],
  },
  {
    companyName: "Erutech",
    rounds: [
      {
        roundNumber: 1,
        roundType: "HR",
        questions: [
          "Tell me about yourself",
          "Why do you want to join Erutech?",
          "Where do you see yourself in the next few years?",
          "Are you comfortable working in a Non-Dream company?",
          "What are your strengths and weaknesses?",
          "How do you handle pressure or tight deadlines?",
          "Are you open to learning new technologies used by the company?",
          "Do you have any questions for us?",
        ],
      },
      {
        roundNumber: 2,
        roundType: "Technical",
        questions: [
          "Explain your projects mentioned in your resume",
          "Explain the complete flow of your website or application",
          "Which programming languages and frameworks did you use?",
          "Which APIs did you use and why?",
          "How did you ensure data accuracy in your project?",
          "What authentication or security mechanism did you use?",
          "Which database did you use and why?",
          "How did you connect frontend with backend?",
          "Where did you deploy your project?",
          "Why did you choose your specific tech stack?",
          "Are you familiar with technologies like GraphQL, GoLang, or Angular?",
        ],
      },
    ],
  },
];


export default mockInterviewData;
